

service: risk-management-server

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  hello:
    handler: app/app.handler
    events:
      - http:
          path: /server
          method: GET
          cors: true
      - http:
          path: /employee/addEmployee
          method: POST
          cors: true
          authorizer: aws_iam
      - http:
          path: /team/{proxy+}
          method: ANY
          cors: true
          authorizer: aws_iam
      - http:
          path: /risk/{proxy+}
          method: ANY
          cors: true
          authorizer: aws_iam
          
          
